url: "kanenstephens.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "kanen stephens" # the name of your site, e.g. ACME Corp.

author: "kanen stephens"
buymeacoffee: "buymeacoffee.com/kanenstephens"
repo: "github.com/kanennn/kanenstephens"

collections_dir: collections
collections:
    column1:
        output: false
        sort_by: pos
    column2:
        output: false
        sort_by: pos
    column3:
        ouput: false
        sort_by: pos
